### PR TITLE
Added Binary Sort Program using Naive Approach

### PR DESCRIPTION
**Pull request by sharathkumar106**
> Added a new Java Program for Binary Sort.
>
Please review the change and merge this PR.
Thank you!

### CODE REVIEW

**Comment by sharathkumar106** [comment]
@pkindalov  Can you please add a "hacktoberfest-accepted" label to the PR for acceptance?

**Comment by pkindalov** [comment]
Sorry mate, I forgot how to do this.

**Comment by sharathkumar106** [comment]
Thanks a lot 😃

**Comment by pkindalov** [comment]
You wellcome :+1:  :)

**Pull request merged**
